package com.teo.store;

import java.util.ArrayList;
import java.util.List;

import com.teo.store.model.*;
import com.teo.store.services.EventService;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.control.Alert;
import javax.swing.SwingUtilities;

/**
 *
 * @author Teodora
 */
public class BuyTickets extends javax.swing.JFrame {
    private EventService eventService = EventService.getInstance();
    private List<Event> eventsList= new ArrayList<>();
    private Consumer client;
    private Ticket clientsTicket = new Ticket();
    /**
     * Creates new form BuyTickets
     */
    public BuyTickets() {
        this.client = new Consumer();
        initComponents();
    }
    public BuyTickets(Consumer consumer) {
        this.client = new Consumer();
        client.setFirstName(consumer.getFirstName());
        client.setLastName(consumer.getLastName());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CinemaRadioButton = new javax.swing.JRadioButton();
        ConcertRadioButton = new javax.swing.JRadioButton();
        TeatruRadioButton = new javax.swing.JRadioButton();
        StandRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EventsList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        ContinuaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        welcomeLabel.setText("Bine ai venit, "+client.getFirstName()+ "!");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("Ce vrei sa achizitionezi ?");

        CinemaRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        CinemaRadioButton.setText("Bilete la cinema");
        CinemaRadioButton.setName("Bilete la cinema"); // NOI18N
        CinemaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CinemaRadioButtonActionPerformed(evt);
            }
        });

        ConcertRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ConcertRadioButton.setText("Bilete la concert");
        ConcertRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcertRadioButtonActionPerformed(evt);
            }
        });

        TeatruRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TeatruRadioButton.setText("Bilete la teatru");
        TeatruRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeatruRadioButtonActionPerformed(evt);
            }
        });

        StandRadioButton.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        StandRadioButton.setText("Bilete la StandUp");
        StandRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(StandRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                        .addComponent(TeatruRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ConcertRadioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CinemaRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CinemaRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ConcertRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TeatruRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StandRadioButton)
                                .addContainerGap(63, Short.MAX_VALUE))
        );

        CinemaRadioButton.getAccessibleContext().setAccessibleDescription("Bilete");

        eventsList = eventService.getEventsList();
        EventsList.setBackground(new java.awt.Color(255, 255, 0));
        EventsList.setBorder(new javax.swing.border.MatteBorder(null));
        EventsList.setFont(new java.awt.Font("Noto Sans Light", 1, 14)); // NOI18N
        EventsList.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        EventsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        EventsList.setListData(eventsList.toArray());
        jScrollPane1.setViewportView(EventsList);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Vizualizeaza evenimentele disponibile:");

        ContinuaButton.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ContinuaButton.setText("Continua");
        ContinuaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ContinuaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(welcomeLabel)
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel2)
                                                .addGap(42, 42, 42)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ContinuaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)))
                                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void CinemaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(CinemaRadioButton.isSelected()){
            TeatruRadioButton.setSelected(false);
            ConcertRadioButton.setSelected(false);
            StandRadioButton.setSelected(false);
        }

    }

    private void TeatruRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(TeatruRadioButton.isSelected()){
            CinemaRadioButton.setSelected(false);
            ConcertRadioButton.setSelected(false);
            StandRadioButton.setSelected(false);
        }
    }

    private void ConcertRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(ConcertRadioButton.isSelected()){
            CinemaRadioButton.setSelected(false);
            TeatruRadioButton.setSelected(false);
            StandRadioButton.setSelected(false);
        }

    }

    private void StandRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(StandRadioButton.isSelected()){
            CinemaRadioButton.setSelected(false);
            TeatruRadioButton.setSelected(false);
            ConcertRadioButton.setSelected(false);
        }
    }
    public List<? extends Event> seeOption(){
        List<? extends Event> myList;
        if(StandRadioButton.isSelected()){
            myList = eventService.getAllStandUps();
        }
        else
        if(ConcertRadioButton.isSelected()){
            myList = eventService.getAllConcerts();
        }
        else
        if(CinemaRadioButton.isSelected()){
            myList = eventService.getAllMovies();
        }
        else
        if(TeatruRadioButton.isSelected()){
            myList = eventService.getAllTheatrePlays();
        }
        else{
            myList = eventService.getEventsList();
        }
        return myList;
    }

    private boolean validation(){
        if(!StandRadioButton.isSelected()&& !ConcertRadioButton.isSelected()&&
                !CinemaRadioButton.isSelected() && !TeatruRadioButton.isSelected())
            return false;

        return true;
    }

    private void ContinuaButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ListEventsByType le = new ListEventsByType(seeOption(),clientsTicket);

        if(StandRadioButton.isSelected()){
            clientsTicket.setEvent(new StandUpShow());
        }
        else
        if(ConcertRadioButton.isSelected()){
            clientsTicket.setEvent(new Concert());
        }
        else
        if(CinemaRadioButton.isSelected()){
            clientsTicket.setEvent(new Movie());
        }
        else
        if(TeatruRadioButton.isSelected()){
            clientsTicket.setEvent(new TheatrePlay());
        }


        if(!validation()){
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new JFXPanel(); // this will prepare JavaFX toolkit and environment
                    Platform.runLater(new Runnable() {
                        @Override
                        public void run() {
                            Alert validationAlert = new Alert(Alert.AlertType.WARNING);
                            validationAlert.setTitle("Ooops, ceva n-a mers bine!");
                            validationAlert.setHeaderText(null);
                            validationAlert.setContentText("Nu ati completat unul dintre campuri.");
                            validationAlert.show();
                        }
                    });
                }
            });
        }
        else
            le.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JRadioButton CinemaRadioButton;
    private javax.swing.JRadioButton ConcertRadioButton;
    private javax.swing.JButton ContinuaButton;
    private javax.swing.JList EventsList;
    private javax.swing.JRadioButton StandRadioButton;
    private javax.swing.JRadioButton TeatruRadioButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration
}
