/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teo.store;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.teo.store.model.Consumer;
import com.teo.store.model.Event;
import com.teo.store.model.Location;
import com.teo.store.services.EventService;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Teodora
 */
public class ConsumerInfo extends javax.swing.JFrame {

    private static final EventService eventService = EventService.getInstance();
    private static List<Event> eventsList = new ArrayList<>();
    private Consumer myConsumer = new Consumer();

    /**
     * Creates new form ConsumerInfo
     */
    public ConsumerInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BirthDateLabel = new javax.swing.JLabel();
        SpinnerNumberModel value = new SpinnerNumberModel(1,1,31,1);
        DaySpinner = new javax.swing.JSpinner(value);
        MonthComboBox = new javax.swing.JComboBox();
        SpinnerNumberModel value2 = new SpinnerNumberModel(1997,1950,2001,1);
        YearSpinner = new javax.swing.JSpinner(value2);
        CountryLabel = new javax.swing.JLabel();
        CountryComboBox = new javax.swing.JComboBox();
        TownLabel = new javax.swing.JLabel();
        TownComboBox = new javax.swing.JComboBox();
        StreetLabel = new javax.swing.JLabel();
        StreetTextField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 51));
        setForeground(new java.awt.Color(0, 255, 0));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setSize(new java.awt.Dimension(600, 400));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setBackground(new java.awt.Color(51, 255, 51));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        NameLabel.setText("Nume:");
        NameLabel.setFocusable(false);
        NameLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        FirstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FirstNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        FirstNameLabel.setText("Prenume:");

        LastNameTextField.setBackground(new java.awt.Color(204, 255, 102));
        LastNameTextField.setToolTipText("Ionescu");
        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        FirstNameTextField.setBackground(new java.awt.Color(153, 255, 102));
        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        EmailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        EmailLabel.setText("Email:");

        EmailTextField.setBackground(new java.awt.Color(204, 255, 102));
        EmailTextField.setText("nume.prenume@yahoo.com");
        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Introduceti datele dumneavoastra:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BirthDateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BirthDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        BirthDateLabel.setText("Data nasterii:");
        BirthDateLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DaySpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DaySpinner.setPreferredSize(new java.awt.Dimension(35, 25));

        MonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ianuarie", "Februarie", "Martie", "Aprilie", "Mai", "Iunie", "Iulie", "August", "Septembrie", "Octombrie" }));
        MonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthComboBoxActionPerformed(evt);
            }
        });

        YearSpinner.setPreferredSize(new java.awt.Dimension(60, 25));

        CountryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CountryLabel.setText("Tara:");

        CountryComboBox.setBackground(new java.awt.Color(153, 255, 153));
        CountryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ","Bulgaria","Franta","Italia","Romania","Spania","Ungaria" }));
        CountryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryComboBoxActionPerformed(evt);
            }
        });

        TownLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TownLabel.setText("Oras:");

        TownComboBox.setBackground(new java.awt.Color(153, 255, 153));
        TownComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ", "Alba Iulia","Arad","Braila","Bucuresti","Buzau","Bacau","Brasov","Cluj","Constanta","Iasi","Targu Mures","Timisoara"}));
        TownComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TownComboBoxActionPerformed(evt);
            }
        });

        StreetLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StreetLabel.setText("Strada:");

        StreetTextField.setBackground(new java.awt.Color(204, 255, 102));
        StreetTextField.setText(" ");
        StreetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetTextFieldActionPerformed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(255, 153, 51));
        RegisterButton.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(102, 102, 0));
        RegisterButton.setLabel("Inregistreaza-te");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(FirstNameTextField)
                                                        .addComponent(LastNameTextField)
                                                        .addComponent(EmailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(BirthDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(StreetLabel)
                                                                                .addGap(41, 41, 41))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(CountryLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(TownLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(StreetTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                                        .addComponent(CountryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(TownComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                                .addGap(22, 22, 22))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(FirstNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BirthDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DaySpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(MonthComboBox)
                                        .addComponent(YearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CountryLabel)
                                        .addComponent(CountryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TownComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TownLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(StreetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(StreetLabel))
                                .addGap(45, 45, 45)
                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(195, 195, 195))
        );

        RegisterButton.getAccessibleContext().setAccessibleName("Inregistreaza-te");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void MonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CountryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void TownComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void StreetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void setConsumerFields(){
        myConsumer.setFirstName(FirstNameTextField.getText());
        myConsumer.setLastName(LastNameTextField.getText());
        myConsumer.setEmail(EmailTextField.getText());
        String s=MonthComboBox.getSelectedItem().toString();
        Integer month = null;
        Date date = new Date();
        switch(s){
            case "Ianuarie":{ month=1;}
            case "Februarie":{ month=2;}
            case "Martie":{ month=3;}
            case "Aprilie":{ month=4;}
            case "Mai":{ month=5;}
            case "Iunie":{ month=6;}
            case "Iulie":{ month=7;}
            case "August":{ month=8;}
            case "Septembrie":{ month=9;}
            case "Octombrie":{ month=10;}
            case "Noiembrie":{ month=11;}
            case "Decembrie":{ month=12;}
            default:{month =12;}
        }
        date.setDate(Integer.parseInt(DaySpinner.getValue().toString()));
        date.setMonth(month);
        date.setYear(Integer.parseInt(YearSpinner.getValue().toString()));
        myConsumer.setBirthDate(date);
        Location consumersLocation = new Location(1,StreetTextField.getText().toString(),TownComboBox.getSelectedItem().toString(),CountryComboBox.getSelectedItem().toString());
        myConsumer.setAddress(consumersLocation);

    }

    private boolean validation(){
        if(LastNameTextField.getText().isEmpty() ||
                FirstNameTextField.getText().isEmpty()||
                EmailTextField.getText().equals("nume.prenume@yahoo.com"))
            return false;
        else
        if(DaySpinner.getValue().equals(1) &&
                MonthComboBox.getSelectedItem().equals("Ianuarie") &&
                YearSpinner.getValue().equals(1997))
            return false;
        else
        if(CountryComboBox.getSelectedItem().equals(" ") ||
                TownComboBox.getSelectedItem().equals(" ") ||
                StreetTextField.getText().equals(" "))
            return false;

        return true;
    }
    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(!validation()){
            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    new JFXPanel(); // this will prepare JavaFX toolkit and environment
                    Platform.runLater(new Runnable() {
                        @Override
                        public void run() {
                            Alert validationAlert = new Alert(AlertType.WARNING);
                            validationAlert.setTitle("Ooops, ceva n-a mers bine!");
                            validationAlert.setHeaderText(null);
                            validationAlert.setContentText("Nu ati completat unul dintre campuri.");
                            validationAlert.show();
                        }
                    });
                }
            });
        }
        else{
            setConsumerFields();
            BuyTickets bt = new BuyTickets(myConsumer);
            bt.show();
        }

    }

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsumerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsumerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsumerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsumerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsumerInfo().setVisible(true);
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel BirthDateLabel;
    private javax.swing.JComboBox CountryComboBox;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JSpinner DaySpinner;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JComboBox MonthComboBox;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JToggleButton RegisterButton;
    private javax.swing.JLabel StreetLabel;
    private javax.swing.JTextField StreetTextField;
    private javax.swing.JComboBox TownComboBox;
    private javax.swing.JLabel TownLabel;
    private javax.swing.JSpinner YearSpinner;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}
